---

require:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.3
  Exclude:
    - 'bin/**'
    - 'db/schema.rb'
    - 'db/migrate/**'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Style/ClassAndModuleChildren:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/LineLength:
  Max: 100

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/AsciiComments:
  Enabled: false